name: user_avatar_generator
description: "package that allows you to generate text-based avatars using various methods like initials, symbolic text, and more. This makes it ideal for apps needing personalized and unique user representations, offering easy integration and rich customization options."
version: 0.0.1
homepage: https://github.com/hashimsaffarini/User_Avatar_Generator.git

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
# Flutter assets
flutter:
  assets:
    - lib/assets/images/
