name: user_avatar_generator
description: "Generates text-based avatars using initials, symbolic text, and more. Ideal for personalized user representations with rich customization."
version: 0.0.3
homepage: https://github.com/hashimsaffarini/User_Avatar_Generator.git

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/assets/images/
