name: user_avatar_generator
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/hashimsaffarini/User_Avatar_Generator.git

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
# Flutter assets
flutter:
  assets:
    - lib/assets/images/
